version: '3.8'

services:
  # Sua aplicação Next.js
  myfinpocket-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myfinpocket_web
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    restart: unless-stopped

  # O n8n para as nossas automações de E-mail / PDF
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n_automations
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=America/Sao_Paulo
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

volumes:
  n8n_data: